project:
  type: book
  output-dir: _book

book:
  title: "Biyoinformatik"
  author: "Emrah Kırdök, Ph.D."
  date: "2023/10/15"
  language: tr
  #favicon: "images/ybva.png"
  reader-mode: true

  #sidebar:
  #  logo: "images/ybva.png"

  page-footer:
    left: |
      Biyoinformatik
      Emrah Kırdök, Ph.D.
    right: |
      Bu kitap lisans üstü seviyede verilen
      İleri Biyoinformatik dersi için
      kaynak olarak kullanılacaktır.
  site-url: https://emrahkirdok.github.io/bioinformatics/
  repo-url: https://github.com/emrahkirdok/bioinformatics/
  
  chapters:
    - index.qmd
    - CONTRIBUTING.md
    
    - part: "Derse Hazırlık"
      chapters:
        - 00-setup/01-truba.qmd
        - 00-setup/02-system.qmd
        - 00-setup/03-command-line.qmd
        - 00-setup/04-markdown-kullanim.qmd
    - part: "Dersler"
      chapters:
        - 01-lectures/01-ynd.qmd
        - 01-lectures/02-fastq-quality-control.qmd
        #- 01-lectures/03-fastq-processing.qmd
        - 01-lectures/04-alignment-variant-calling-01.qmd
        - 01-lectures/05-alignment-variant-calling-02.qmd
        - 01-lectures/07-rnaseq.qmd
        - 01-lectures/09-rnaseq-analysis.qmd
        - 01-lectures/08-metagenomics.qmd
        - 01-lectures/06-bash-scripting.qmd
    - part: "Pratikler"
      chapters: 
        - 02-practice/01-variant-practice.qmd
        - 02-practice/02-rnaseq-project.qmd
        - 02-practice/03-metagenomics.qmd
      
    - references.qmd
  appendices:
    - 10-appendices/software-used.qmd

bibliography : bibliography.bib
lang: tr

language:
  tr:
    crossref-fig-title: "Şekil"

format:
  html:
    mainfont: helvetica
    theme:
      - darkly
    code-link: true
  pdf:
    documentclass: scrbook
    author-meta: "Emrah Kırdök"
    margin-left: 2.5cm
    margin-right: 2.5cm
